Script started on Wed 22 Nov 2017 04:20:30 PM PST
]0;haquem1@laguna:~/hw4[haquem1@laguna ~/hw4]$ exitmake clean[25Gvalgrind --leak-check=full ./PhotoLabTest[25Gmake clean[K[25Gexit[K[Kexitmake clean[25Gvalgrind --leak-check=full ./PhotoLabTest[25G./PhotoLab[K[25Gmake[K
make: Nothing to be done for `all'.
]0;haquem1@laguna:~/hw4[haquem1@laguna ~/hw4]$ makeexitmake clean[25Gvalgrind --leak-check=full ./PhotoLabTest[25G./PhotoLab[K

----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image(not implemented)
11: Add Noise to an image
12: Sharpen an image
13: Posterize an image
14: Blur an image(not implemented)
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 19
AutoTest finished successfully.
----------------------------
 1: Load a PPM image
 2: Save an image in PPM and JPEG format
 3: Change a color image to Black & White
 4: Make a negative of an image
 5: Color filter an image
 6: Sketch the edge of an image
 7: Shuffle an image
 8: Flip an image vertically
 9: Mirror an image vertically
10: Add border to an image(not implemented)
11: Add Noise to an image
12: Sharpen an image
13: Posterize an image
14: Blur an image(not implemented)
15: Crop an image
16: Resize an image
17: Adjust the Brightness and Contrast an image
18: Add Watermark to an image
19: Test all functions
20: Exit
Please make your choice: 20
You exit the program.
]0;haquem1@laguna:~/hw4[haquem1@laguna ~/hw4]$ ./PhotoLab[25Gmake[Kexitmake clean[25Gvalgrind --leak-check=full ./PhotoLabTest[26Gim PhotoLab.c[K[26Galgrind --leak-check=full ./PhotoLabTest
==169551== Memcheck, a memory error detector
==169551== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==169551== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==169551== Command: ./PhotoLabTest
==169551== 
==169551== Warning: client switching stacks?  SP change: 0x7fed40f30 --> 0x7ff0001d0
==169551==          to suppress, use: --max-stackframe=2880160 or greater
==169551== 
==169551== HEAP SUMMARY:
==169551==     in use at exit: 0 bytes in 0 blocks
==169551==   total heap usage: 115 allocs, 115 frees, 15,241,603 bytes allocated
==169551== 
==169551== All heap blocks were freed -- no leaks are possible
==169551== 
==169551== For counts of detected and suppressed errors, rerun with: -v
==169551== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;haquem1@laguna:~/hw4[haquem1@laguna ~/hw4]$ valgrind --leak-check=full ./PhotoLabTest[25G./PhotoLab[K[25Gmake[Kexitmake clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm negative.ppm colorfilter.ppm edge.ppm vflipflip.ppm shuffle.ppm vmirror.ppm border.ppm noise.ppm sharpen.ppm posterize.ppm blur.ppm smallresize.ppm bigresize.ppm crop.ppm brightnessandcontrast.ppm watermark.ppm  libFilter.a libFileIO.a
]0;haquem1@laguna:~/hw4[haquem1@laguna ~/hw4]$ exit
exit

Script done on Wed 22 Nov 2017 04:21:51 PM PST
