Script started on Sat 09 Dec 2017 04:21:18 PM PST
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ make
gcc -g -ansi -Wall -c MovieLab.c -o MovieLab.o
gcc -g -ansi -Wall -c  ImageList.c -o ImageList.o
gcc -g -ansi -Wall -DMAIN MovieLab.o FileIO.o Image.o ImageList.o Movie.o DIPs.o -o MovieLab
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ ./MovieLab -h

Usage: MovieLab -i <file> -o <file> -f <framenum> -s <WIDTHxHEIGHT> [options]
Options:
-aging                Activate the aging filter on every movie frame
-hflip                Activate horizontal flip on every movie frame
-edge                 Activate the edge filter on every movie frame
-crop <start-end>     Crop the movie frames from <start> to <end>
-fast <factor>        Fast forward the movie by <factor>
-reverse              Reverse the frame order of the input movie
-watermark <file>     Add a watermark from <file> to every movie frame
-spotlight            Spotlight the fade in and fade out
-zoom                 Zoom in and out the input movie
-h                    Display this usage information
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ ./Moviel[KLab -i mouse.yuv -o out.yub [Kv -f 50 -s 480x270 -aging -hflip
The movie file mouse.yuv has been read successfully!
Operation Aging is done!
Operation HFlip is done!
The movie file out.yuv has been written successfully!
50 frames are written to the file out.yuv in total.
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270 -aging -hflip[K[K[K[K[K[K[K[K[K[K[Kedge
The movie file mouse.yuv has been read successfully!
Operation Edge is done!
The movie file out.yuv has been written successfully!
50 frames are written to the file out.yuv in total.
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270 -edge[K[K[K[Kfast 3 -crop 40-50[K[K[K[K[K10 -[K-40
The movie file mouse.yuv has been read successfully!
Operation Crop is done! New number of frames is 31
Operation Fast is done! New number of frames is 5
Segmentation fault (core dumped)
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270 -fast 3 -crop 10-40[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kreverse
The movie file mouse.yuv has been read successfully!
Operation Reverse is done!
MovieLab: Image.c:179: GetPixelY: Assertion `YUVimage->U' failed.
Abort (core dumped)
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270 -reverse[K[K[K[K[K[K[Kwatermark watermark
The movie file mouse.yuv has been read successfully!
Operation Watermark is done!
The movie file out.yuv has been written successfully!
50 frames are written to the file out.yuv in total.
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ ./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270 -watermark watermark[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kspotlight
The movie file mouse.yuv has been read successfully!
The movie file out.yuv has been written successfully!
50 frames are written to the file out.yuv in total.
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ valgrin[K[K[K[K[K[K[K./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270 -spotlight[K[K[K[K[K[K[K[K[K[K[1@v[1@a[1@l[1@g[1@r[1@i[1@n[1@d[1@ 
==46635== Memcheck, a memory error detector
==46635== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==46635== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==46635== Command: ./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270
==46635== 
^C==46635== 
==46635== HEAP SUMMARY:
==46635==     in use at exit: 11,277,848 bytes in 147 blocks
==46635==   total heap usage: 175 allocs, 28 frees, 11,293,752 bytes allocated
==46635== 
==46635== LEAK SUMMARY:
==46635==    definitely lost: 0 bytes in 0 blocks
==46635==    indirectly lost: 0 bytes in 0 blocks
==46635==      possibly lost: 0 bytes in 0 blocks
==46635==    still reachable: 11,277,848 bytes in 147 blocks
==46635==         suppressed: 0 bytes in 0 blocks
==46635== Rerun with --leak-check=full to see details of leaked memory
==46635== 
==46635== For counts of detected and suppressed errors, rerun with: -v
==46635== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)

]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ valgrind ./MovieLab -i mouse.yuv -o out.yuv -f 50 -s 480x270[P[P[1@1[1@0[1@0[1@\[P[P[P[P[P[P[P[P[P[P./MovieLab -i mouse.yuv -o out.yuv -f 100 -s 480x270 -zoom
The movie file mouse.yuv has been read successfully!
Operation Zoom is done!
The movie file out.yuv has been written successfully!
100 frames are written to the file out.yuv in total.
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ make clean
rm -f *.o *.yuv MovieLab
]0;haquem1@zuma:~/hw5[haquem1@zuma ~/hw5]$ exit
exit

Script done on Sat 09 Dec 2017 04:24:29 PM PST
